name: Android CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Add signature to APKs
      - name: release apk sign
        run: |
          echo "给apk增加签名"
          sed '$a\RELEASE_STORE_FILE=$GITHUB_WORKSPACE/signing.jks' $GITHUB_WORKSPACE/gradle.properties -i
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/app/build/outputs/apk/release
        # The desired behavior if no files are found using the provided path.
